### ISSUE TITLE
"Presets for grass collisons" Install step needs to be updated

### ISSUE THREAD

**Issue by magicalbeard** [ragley/Ragleys-STR#3]
Following the install instructions in the README:

- Extract the "Presets for grass collisons" archive in your Game Files Folder where MO2 is located.

I don't see this archive or the mod in the mods folder, it appears it was downloaded by wabbajack, but I'm unsure if there is still a further install step needed here or if there is just an update needed to the install instructions.

**Comment by ragley** [comment]
Fixed. Thank you for catching that, wabbajack now automates this and it was leftover from a previous version.
